var yeoman = require('yeoman-generator');
var slugify = require('slugify');

module.exports = yeoman.generators.Base.extend({
    promptForProjectName: function () {
        var done = this.async();
        var prompts = [
            {
                name: 'projectName', message: 'What is the name of your project?', default: this.appname
            },
            {
                name: 'projectDescription', message: 'What is the description of your project?', default: 'Autogenerated Node/Express Template'
            },
            {
                name: 'serverPort', message: 'Which port should the server run on?', default: '4000'
            },
            {
                name: 'loggingType', message: 'What logging would you like?', type: 'list', choices: [
                { value: 'console', name: 'console.log'},
                { value: 'winston', name: 'Winston'}
            ]
            }
        ];
        this.prompt(prompts, function (props) {
            this.projectName = slugify(props.projectName, '-');
            this.projectDescription = props.projectDescription;
            this.serverPort = props.serverPort;
            var hasMod = function (mod) { return props.loggingType.indexOf(mod) !== -1; };
            this.logOption = hasMod('console') ? 'console.log':this.logOption;
            this.logOption = hasMod('winston') ? 'logger.info':this.logOption;
            done();
        }.bind(this));
    },
    copyFiles: function () {
        var done = this.async();

        this.template('_package.json', 'package.json');
        this.template('_server.js', 'server.js');
        done();
    },
    performNpmInstall: function () {
        var done = this.async();
        this.npmInstall();
        done();
    }
});
