var yeoman = require('yeoman-generator');
var slugify = require('slugify');

module.exports = yeoman.generators.Base.extend({
  promptForProjectName: function () {
    var done = this.async();
    var prompts = [
      {
        name: 'projectName', message: 'What is the name of your project?', default: this.appname
      },
      {
        name: 'projectDescription', message: 'What is the description of your project?', default: 'Autogenerated Node/Express Template'
      },
      {
        name: 'serverPort', message: 'Which port should the server run on?', default: '4000'
      },
      {
        name: 'mongoHost', message: 'Hostname of the mongo instance?', default: 'localhost'
      },
      {
        name: 'mongoPort', message: 'Port of the mongo instance?', default: 27017
      },
      {
        name: 'mongoDb', message: 'DB of the mongo instance?', default: 'testdb'
      },
      {
        name: 'entity', message: 'Entity to create?', default: 'person'
      },
      {
        name: 'entityPlural', message: 'Plural name for entity?', default: 'people'
      },
      {
        name: 'loggingType', message: 'What logging would you like?', type: 'list', choices: [
        { value: 'console', name: 'console.log'},
        { value: 'winston', name: 'Winston'}
      ]
      }
    ];
    this.prompt(prompts, function (props) {
      this.projectName = slugify(props.projectName, '-');
      this.projectDescription = props.projectDescription;
      this.serverPort = props.serverPort;
      this.mongoHost = props.mongoHost;
      this.mongoPort = props.mongoPort;
      this.mongoDb = props.mongoDb;
      this.entity = props.entity;
      this.entityPlural = props.entityPlural;
      var hasMod = function (mod) {
        return props.loggingType.indexOf(mod) !== -1;
      };
      this.logOption = hasMod('console') ? 'console.log' : this.logOption;
      this.logOption = hasMod('winston') ? 'logger.info' : this.logOption;
      done();
    }.bind(this));
  },
  copyFiles: function () {
    var done = this.async();

    this.template('_package.json', 'package.json');
    this.template('_server.js', 'server.js');
    this.template('config/_default.json', 'config/default.json');
    this.template('models/_default.js', 'models/default.js');
    done();
  },
  performNpmInstall: function () {
    var done = this.async();
    this.npmInstall();
    done();
  }
});
